language: java
jdk: oraclejdk8
script: mvn clean package
deploy:
  provider: heroku
  api_key:
    secure: Ec0otS565jyDxwfbyoOqpozoEHAZcvjMxEFOtvkZ1Fop7ZC0Ww6gDN+BjtYolV5pnfJp9eddezSnsF15dl1H+WuL3BvaegS6q92yPUIHqIFg8NKvpUd53u//9ccw9NGy2Di1UhsNnkgsrCh2cPnNxPFfQlEVrnYKS0CVQtpj24JgJzjH3MhZ4vNBo3rpygm6ANseBa/527a14MKKJ1z8MztC/jPhVBisGEVVEde/cKD8u9fwlqAs1cVzDlAlgochYzayNh3b727OXJT6t+XZsMj2OAOlIuD0opTPR1m2Z5KyXRW0E5v/U3k7btetW21zwNwjeYSlYkJ8UhmdI0IJr8pFspnO2JBvWEq6kAuNqhxsSMVXbnCwxw9u9cdlkrvkjbSWEB/wLQzTtlzDskKOtFahWDtgfyCZoiOH58dv6Jn5BULrH0pXkYxNUiQ2EpEC0eRvdxsu9GLuaFG9sgngxYS7r3qr5lkSXXu6xTwxLc9K+2fBfcCA++A68heC9W0ikr/OILRU5L4WeWfX1a5wsYmK7efLLyY8ZmOLeJWx1QHxjgNVI6UcT7MsryV3WiLx+BmV0x65oIAipicsQQHmvh0Ls9LseEaBBkkwt+2vHdvVtctqyBpUf7JzMM/JHaZyNtpMxBsEnfq7j0idTRQ3EAY2Th748ZYgzFdw35lNHPc=
  app: spring-websoc
  on:
    repo: arpitjindal97/spring-websocket
